import { useEffect } from "react";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import { useRouter } from "next/router";

import { useSession, signIn, signOut } from "next-auth/react";
import Sidebar from "../components/sidebar";
import Dashboard from "../components/Dashboard";

export default function Home() {
  const { data: session } = useSession();
  const router = useRouter();
  console.log(session);

  useEffect(() => {
    // Redirect to login page if there is no session
    if (!session) {
      router.push("/Login");
    }
  }, [session, router]);

  if (session) {
    return (
      <div className={styles.container}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main>
          <div class="flex h-screen ">
            <Sidebar />
            <Dashboard />
          </div>
        </main>
      </div>
    );
  }
}
